#Play1
- name: This is our first play
  hosts: webservers
  become: true
  tasks:
    - name: sleep for 120 seconds
      command: sleep 120

    - name: create a dummy file on webserver
      command: touch /tmp/ansible_dummy.txt
