#Play1
- name: This is our first play
  hosts: dbservers
  become: true
  tasks:
    - name: install apache2
      apt: 
        name: apache2
        state: latest
        update_cache: yes

    - name: create a dummy file on webserver
      command: touch /tmp/ansible_dummy.txt
