#Play1
- name: This is our first play
  hosts: webservers
  become: true
  vars: 
    servicename: apache2
  tasks:
    - name: install apache
      apt: 
        name: apache2     
        state: latest
        update_cache: yes 
    - name: start apache service
      service: 
        name: "{{ servicename }}"
        state: started
